MAX_ITERATIONS = 300
FPS = 5

ENABLE_MORALE = True
TEAM_MORALE_COLLAPSE_THRESHOLD = 20

SCREEN_WIDTH = 500
SCREEN_HEIGHT = 1000
GRID_SIZE = 25
MAP_WIDTH = SCREEN_WIDTH // GRID_SIZE
MAP_HEIGHT = SCREEN_HEIGHT // GRID_SIZE

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (192, 57, 43)
GREY = (128, 128, 128)
IMMORTAL_COLOR_RANGED = (52, 73, 94)
IMMORTAL_COLOR_MELEE = (102, 51, 0)

HP_BAR_COLOR = (0, 200, 0)
MORALE_BAR_COLOR = (200, 200, 0)
BAR_BACKGROUND_COLOR = (70, 70, 70)
STATUS_BAR_HEIGHT = 3
STATUS_BAR_PADDING = 2

DEFAULT_MORALE = 80

LOW_MORALE_TARGET_DAMAGE_MULTIPLIER = 1.20
ROUTING_TARGET_CRITICAL_MULTIPLIER = 1.50

ATTACKER_CRITICAL_MORALE_DAMAGE_PENALTY = 0.75

HIT_CHANCE = 0.80
DAMAGE_VARIANCE_MIN = 0.85
DAMAGE_VARIANCE_MAX = 1.15

FLANK_BONUS = 1.25
REAR_ATTACK_BONUS = 1.5

ENABLE_LANCHESTER_SQUARE_BONUS = True
LANCHESTER_RANGED_SUPPORT_RADIUS = 4
LANCHESTER_RANGED_BONUS_PER_SUPPORTING_UNIT = 0.015
LANCHESTER_MAX_RANGED_CONCENTRATION_BONUS = 0.20

MORALE_ALLY_FALLEN_RADIUS = 4
MORALE_ALLY_FALLEN_PENALTY = -2
MORALE_HP_50_PERCENT_PENALTY = -10
MORALE_HP_20_PERCENT_PENALTY = -15
MORALE_SURROUNDED_THRESHOLD = 3
MORALE_SURROUNDED_RADIUS = 2
MORALE_SURROUNDED_PENALTY = -20
MORALE_LOW_THRESHOLD = 35
MORALE_LOW_EFFECT_PENALTY = 0.20
MORALE_FLEE_CHANCE = 0.10
MORALE_ROUT_THRESHOLD = 10

TOTAL_PERSIAN_COUNT = 300
PERSIAN_INITIAL_AMMO = 3
PERSIAN_RANGED_ATTACK_POWER = 20
PERSIAN_RANGED_ATTACK_RANGE = 5
PERSIAN_MELEE_ATTACK_POWER_WEAK = 15
PERSIAN_INFANTRY_HP = 50
PERSIAN_INFANTRY_DEFENSE = 3
PERSIAN_ATTRITION_MORALE_PENALTY = -8
PERSIAN_ATTRITION_CASUALTY_THRESHOLDS = [0.15, 0.30, 0.45, 0.60]

TOTAL_SPARTAN_COUNT = 40
SPARTAN_HP_REGEN_RATE = 0.38
SPARTAN_MORALE_REGEN_RATE = 0.8
SPARTAN_MAX_MORALE_CAP = 150
